const uuid = require("uuid/v4");

export enum CardActionTypes {
  ADD_REQUEST = "ADD_REQUEST",
  ADD_REQUEST_SUCCESS = "ADD_REQUEST_SUCCESS",
  REMOVE_REQUEST = "REMOVE_REQUEST",
  REMOVE_SUCCESS = "REMOVE_REQUEST",
  CHECKOUT_REQUEST = "CHECKOUT_REQUEST",
  CHECKOUT_REQUEST_SUCCESS = "CHECKOUT_REQUEST_SUCCESS",
  CHECKOUT_REQUEST_FAILURE = "CHECKOUT_REQUEST_FAILURE"
}

export enum ProductsActionsTypes {
  INCREASE_PRO_QUA_REQUEST = "INCREASE_PRO_QUA_REQUEST",
  INCREASE_PRO_QUA_SUCCESS = "INCREASE_PRO_QUA_SUCCESS",
  DECREAESE_PRO_QUA_REQUEST = "DECREASE_PRO_QUA_REQUEST",
  DECREAESE_PRO_QUA_SUCCESS = "DECREASE_PRO_QUA_SUCESS"
}

export enum ProductIds {
  Pizza = uuid(),
  Sushi = uuid(),
  Steak = uuid()
}
